### ISSUE TITLE
GL-E750 Version 2

### ISSUE THREAD

**Issue by jans23** [srlabs/blue-merle#23]
The current version of GL-E750 for Europe is sold out and not available anymore. GL said a version 2 will become available in one month from now. Do you plan to support that as well?

**Comment by muelli** [comment]
The device's firmware is the same as for v1, so there shouldn't be any problems on that end. The difference is with the modem. What modem do you have? There's a sticker on your device, something like "EM05-G".

**Comment by muelli** [comment]
ah, you mentioned "EM060K", sorry for the noise. Our current testing device has a EM05-G modem. I wonder how many different modems they used to make the v2. I'm currently in the process of assessing whether the EM05-G works as expected. I'll let you know shortly.

**Comment by easthvan** [comment]
@muelli currently I still have the gene but I will buy a lots of gene soon and that will come with EM060K modem inside. What is your view on that?

**Comment by easthvan** [comment]
> ah, you mentioned "EM060K", sorry for the noise. Our current testing device has a EM05-G modem. I wonder how many different modems they used to make the v2. I'm currently in the process of assessing whether the EM05-G works as expected. I'll let you know shortly.

🙏
Honestly, they call both,  the EM05-G and EP06 as V1 (1st gen) but variants while they refer to this coming EM060K variant as V2 (2nd gen).  [https://www.quectel.com/product/lte-a-em060k-series]

@muelli At this point let me pinpoint something very important regarding privacy and anonymity with these modems: they have built in GPS chips! Although the V1 has no working firmware support or so, but it's a huge issue, concern. I'll try to read after this, and maybe remove the GPS chip or so...

**Comment by easthvan** [comment]
> ah, you mentioned "EM060K", sorry for the noise. Our current testing device has a EM05-G modem. I wonder how many different modems they used to make the v2. I'm currently in the process of assessing whether the EM05-G works as expected. I'll let you know shortly.

For your reference, below is a link to the (not that 100% public) hardware design documentation (80 pages pdf) for the EM060K for the new 2nd gen GL750 Mudi: [](https://thewirelesshaven.com/wp-content/uploads/2023/04/Quectel_EM060K-GLEM120K-GL_Hardware_Design_V1.0.0_Preliminary_20211229.pdf) and also a photo for the GPS antenna connection here: [](https://thewirelesshaven.com/wp-content/uploads/2021/01/Quectel-EM06-A-CAT6-M.2-Modem-Antenna-Pairs.png)

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
@jans23

We've some for about a month now: https://shop.proxysto.re/conf/820

@muelli @easthvan

The Mudi v2 is available with CAT 4 EM05-G or CAT 6 EM060K LTE modules. [archive.org:gl-inet.com/products/gl-e750/](https://web.archive.org/web/20231030123310/https://www.gl-inet.com/products/gl-e750/)

I don't know why they only mention the CAT 6 EM060K LTE module on the current product page.

In the [data sheet](https://static.gl-inet.com/www/images/products/datasheet/e750v2_datasheet_20230808.pdf) they write "CAT4/CAT6" and we have received some with the CAT 4 EM05-G module.

@easthvan

The previous LTE modules from Quectel (EC25, EG25, EP06) also all had optional GNSS (GPS, ...) support.

**Comment by muelli** [comment]
FTR: v2 with the EM05-G modem works as expected.

**Comment by easthvan** [comment]
> FTR: v2 with the EM05-G modem works as expected.

The EM060K variant of the E750V2 is also coming soon. I'm trying to get one. 

Assuming that the PCB and the firmware is the same, does it make any difference for blue Merle? Maybe the MCU program is not identical? Does blue merle modify the MCU file as well? (I've some mysterious display issues due to not yet determined reasons).

**Comment by muelli** [comment]
> Assuming that the PCB and the firmware is the same, does it make any difference for blue Merle?

Not for the package itself. But the modem may not support the instructions we depend on or behave differently.

**Comment by easthvan** [comment]
> > Assuming that the PCB and the firmware is the same, does it make any difference for blue Merle?
> 
> Not for the package itself. But the modem may not support the instructions we depend on or behave differently.

We are trying to get from the latest EM060K variant as well with @b068931cc450442b63f5b3d276ea4297 (https://github.com/srlabs/blue-merle/issues/23#issuecomment-1863476546) ASAP.  Hopefully that variant will work too.

**Comment by TheWanderer1983** [comment]
> > Assuming that the PCB and the firmware is the same, does it make any difference for blue Merle?
> 
> Not for the package itself. But the modem may not support the instructions we depend on or behave differently.

Here is the AT manual for the EM060K 
https://s3-us-west-2.amazonaws.com/files.seeedstudio.com/products/113990854/res/Quectel_EP06%26EG06%26EM06_AT_Commands_Manual_V1.0.pdf

and here is the EM050-G 
https://www.quectel.com/wp-content/uploads/pdfupload/Quectel_EC2x&EG9x&EG2x-G&EM05_Series_AT_Commands_Manual_V2.0.pdf

**Comment by jans23** [comment]
@muelli @kantorkel @rieck-srlabs @Linuzifer Any update on this?

**Comment by muelli** [comment]
Blue-merle works with the EM05-G modem. We assume that the EM060K modem works as well, but we have not yet been able to actually test it.

**Comment by easthvan** [comment]
> Blue-merle works with the EM05-G modem. We assume that the EM060K modem works as well, but we have not yet been able to actually test it.

I'll test it in February and come back to this thread with the results. If it's negative, I'd send the unit for you.

**Comment by nestire** [comment]
We tested the EM060K variant and it works

**Comment by easthvan** [comment]
> We tested the EM060K variant and it works, as expected so this can be closed

THANK YOU FOR STARING THE GOOD NEWS! 🙏

**Comment by anton2025brown** [comment]
sorry im new to this im looking for a pre built v2 blue merle file  or im just stuck because i got a V2 I FEEL LOST  any help or fo i really have to build the file my self my pc is so slow  sorry for my english

**Comment by muelli** [comment]
You can go to the [releases tab](https://github.com/srlabs/blue-merle/releases/tag/v3.0) and get the ipk file from there:
https://github.com/srlabs/blue-merle/issues/23#issuecomment-3332763824

<img width="353" height="115" alt="Image" src="https://github.com/user-attachments/assets/bd5f6a03-9d8e-4c17-93bb-34a8db427d52" />
