### ISSUE TITLE
Display and UI should show correct number of WiFi clients instead of zero

### ISSUE THREAD

**Issue by roon2010** [srlabs/blue-merle#3]
Nice job, i just install and works nice.
I see the led screen don't show any clients anymore after the install, and at the admin panel also no clients connect.

**Comment by Linuzifer** [comment]
Hey @roon2010,

I am glad the install worked fine for you.

If I understand correctly, you observe that the LED display and admin panel to not display any info about connected clients.
**This proves that our patch erases all traces of them.** (see section 3.2 of the [Documentation](https://github.com/srlabs/blue-merle/blob/main/Documentation.pdf)
So, the issue you're describing seems to be in the _"it's a feature"_ dimension :)

It should probably be possible to query the information from the process and display it.
However, this touches areas of the mudi code that we're not familiar with.

How important is it to you to have the information on the display?

**Comment by roon2010** [comment]
Hello Linuzifer,

For me its not a problem.
I have seen that the LUCI panel there we can see the connected clients.
But i am oke with it like this.
Very nice job.
