### ISSUE TITLE
Unlocked carrier

### ISSUE THREAD

**Issue by richoffpints** [srlabs/blue-merle#33]
So beffore i buy the mudi i just wana make this clear, by changing the imei, this DOES make it so i can use any carrier like trac phone or simple mobile, ect.? Esspesaly with the feater of the imei and imsi being changed in relation to the sim correct? I just dont wana pull the trigger and still be locked to t mobile

**Comment by Linuzifer** [comment]
Blue merle has absolutely nothing to do with carrier locking. To my knowledge, the device is not even sold with a carrier lock.

**Comment by richoffpints** [comment]
Ok i see  have you guys testest this on mudi v2?

**Comment by Linuzifer** [comment]
Please read the friendly manual and please reserve Github‘s issue-functionality for issues and discussions about issues.

**Comment by ali-master** [comment]
Hello,

The GL-E750V2 device's carrier is restricted in Iran and other sanctioned nations.

Could you assist us in resolving this issue and unlocking it?

@Linuzifer
