### ISSUE TITLE
Installing Blue merle with firmware version 4.3.19

### ISSUE THREAD

**Issue by FloatingLizard** [srlabs/blue-merle#49]
I just receive the Mudi V2 and attempted to install the Blue Merle and it failed.

Is it not compatible with the latest firmware? running firmware version 4.3.19
at the end I have to choose Y or N and within a split of a second it gives the error.

Package coreutils (9.0-2) installed in root is up to date.
Updating database.
Database update completed.
Package coreutils-shred (9.0-2) installed in root is up to date.
Updating database.

Database update completed.
Package libpython3-3.10 (3.10.9-1) installed in root is up to date.
Updating database.
Database update completed.
Package python3-base (3.10.9-1) installed in root is up to date.
Updating database.
Database update completed.
Package libffi (3.4.2-2) installed in root is up to date.
Updating database.
Database update completed.
Package libbz2-1.0 (1.0.8-1) installed in root is up to date.
Updating database.
Database update completed.
Package python3-light (3.10.9-1) installed in root is up to date.
Updating database.
Database update completed.
Package python3-pyserial (3.4-2) installed in root is up to date.
Updating database.
Database update completed.
Installing blue-merle (2.0.0-0) to root...
Version 4.3.19 is *probably* supported

You have a GL.iNet GL-E750, running firmware version 4.3.19.
blue-merle has only been tested with GL-E750 Mudi Version 4.3.8.
The device or firmware version you are using have not been verified to work with blue-merle.
Would you like to continue on your own risk? (y/N): Collected errors:
 * pkg_run_script: package "blue-merle" preinst script returned status 1.
 * preinst_configure: Aborting installation of blue-merle.
 * opkg_install_cmd: Cannot install package blue-merle.
./install.sh: line 29: blue-merle: not found
root@GL-E750:/tmp/blue_merle_install#

**Comment by muelli** [comment]
How exactly are you trying to install the package? Through an SSH connection or through the Web interface?

And which file are you trying to install exactly?

**Comment by FloatingLizard** [comment]
Hi,

  I did it via SSH and I used the offline install method 
  and did
  cd /tmp/blue_merle_install
./install.sh

  I am just trying to change the IMEI.

**Comment by FloatingLizard** [comment]
I used the online method and it has changed the IMEI  successfully..
