### ISSUE TITLE
`Documentation.pdf`: clarify IMEI generation method for toggle button approach

### ISSUE THREAD

**Issue by 6t8k** [srlabs/blue-merle#6]
In [Documentation.pdf](https://github.com/srlabs/blue-merle/blob/main/Documentation.pdf?raw=true), sections 4.2 and 4.2.2 (`blue-merle` command) mention that the new IMEI is generated either randomly or deterministically, but section 4.2.1 (toggle button) does not mention how the new IMEI is generated at all (although [README.md](https://github.com/srlabs/blue-merle/blob/main/README.md) does mention it) - perhaps this could be clarified.

**Comment by rieck-srlabs** [comment]
Thanks for the feedback!

Section 4.2.2 of the updated [Documentation.pdf](https://github.com/srlabs/blue-merle/blob/main/Documentation.pdf?raw=true) now clarifies that IMEIs are randomly generated when using the toggle switch approach.
