### ISSUE TITLE
FYI: `blue-merle` should be compatible with GL-E750 Mudi version 3.217

### ISSUE THREAD

**Issue by 6t8k** [srlabs/blue-merle#8]
`blue-merle` should be compatible with GL-E750 Mudi version 3.217 from 2023-05-08 02:41:42 (UTC+00:00) / sha256: `5dab717c1b418b5da4613bce6d82949d9a3defadc53e660fef08d1febe6e93d3` [(from here)](https://dl.gl-inet.com/?model=e750).

This is how I performed the update and arrived at this conclusion:

0. Initial condition: GL-E750 Mudi version 3.215 with `blue-merle_1.0.0-1_mips_24kc.ipk` installed
1. Uninstalled `blue-merle_1.0.0-1_mips_24kc.ipk`
2. Updated GL-E750 Mudi to version 3.217
3. The following files are the only ones that already exist without `blue-merle`, and are modified by it. `diff`'d those after step 2 against the versions of them after step 1 - there were zero differences:
    1. `/www/src/temple/settings/index.html`
    2.  `/www/src/temple/settings/index.js`
    3. `/usr/bin/switchaction`
    4. `/usr/bin/switch_queue`
5. Installed `blue-merle_1.0.0-1_mips_24kc.ipk`
6. Did a superficial check of the admin panel to see if the change introduced by `blue-merle` looks as it should
7. Executed the pysical toggle button variant of generating and assigning a different IMEI, which still worked
8. Used the Mudi for a couple of days without issues

Please note, however, that this does not prove that everything works as it should. **Use this information at your own risk.**

**Comment by mollyuser** [comment]
Is there anywhere a video or a noob explaination on how to install this to the mudi ? Can this be done by using a macbook? And after the bkue merle is installed, can u switch imei without connecting the mudi back to a laptop and use commands? Hope someone can help a noob

**Comment by muelli** [comment]
> Is there anywhere a video or a noob explaination on how to install this to the mudi ? Can this be done by using a macbook? And after the bkue merle is installed, can u switch imei without connecting the mudi back to a laptop and use commands? Hope someone can help a noob

it can certainly be done with a Macbook. Currently, you need to copy the .ipkg onto the device (most likely via scp), then SSH onto the device and install the .ipkg. It should also be possible to upload the .ipkg through the OpenWRT web interface (System → Advanced Settings → System → Software) and install from there.

And yes, the hardware switch allows for the changing the IMEI without having to touch a computer by toggling the hardware switch.

**Comment by muelli** [comment]
Let me close this because the check has been relaxed in [this PR](https://github.com/srlabs/blue-merle/pull/10).
